accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('verify-phone/', views.CheckTopView.as_view(), name='check_otp'),
    path('login/', views.LoginView.as_view(), name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

from django.conf import settings as conf_settings
from django.conf.urls.static import static

if conf_settings.DEBUG:
    urlpatterns += static(conf_settings.STATIC_URL, document_root=conf_settings.STATIC_ROOT)
    urlpatterns += static(conf_settings.MEDIA_URL, document_root=conf_settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .manager import UserManager
from django.core.validators import RegexValidator

# regex phone number
phone_number_validation = RegexValidator(
    regex=r'^[0][9]\d{9}$',
    message='Please Enter A Valid Phone Number'
)


class User(AbstractBaseUser):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True, null=True, blank=True)
    phone = models.CharField(max_length=11, validators=[phone_number_validation], unique=True)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def has_perm(self, perm, obj=None):
        if self.is_superuser:
            return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        if self.is_superuser:
            return True

    def full_name(self):
        if self.first_name and self.last_name:
            return f'{self.first_name} {self.last_name}'
        else:
            return self.phone


class Otp(models.Model):
    phone = models.CharField(max_length=11)
    code = models.SmallIntegerField()
    expiration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.phone

accounts/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import authenticate
from .models import *


# this form is for adding user in admin panel
class UserCreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone']

    def clean_password2(self):
        data = self.cleaned_data
        if data['password2'] and data['password1'] and data['password2'] != data['password1']:
            raise forms.ValidationError('check password please')
        return data['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField

    class Meta:
        model = User
        fields = ['phone']

    def clean_password(self):
        return self.initial['password']


class RegisterForm(forms.Form):
    phone = forms.CharField(
        label='Phone',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '09*********'
            }
        ),
        validators=[
            validators.MaxLengthValidator(11),
        ]
    )
    # password = forms.CharField(
    #     label='Password',
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Password'
    #         }
    #     ),
    #     validators=[
    #         validators.MinLengthValidator(8)
    #     ]
    #
    # )
    # confirm_password = forms.CharField(
    #     label='Confirm Password',
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Confirm Password'
    #         }
    #     ),
    #     validators=[
    #         validators.MinLengthValidator(8)
    #     ]
    # )

    def clean_phone(self):
        phone_number = self.cleaned_data['phone']
        if User.objects.filter(phone__exact=phone_number):
            raise forms.ValidationError('Phone Is Exists')
        return phone_number

    # def clean_confirm_password(self):
    #     password = self.cleaned_data['password']
    #     confirm_password = self.cleaned_data['confirm_password']
    #
    #     if password != confirm_password:
    #         raise forms.ValidationError('Passwords Are Not Match')
    #     return confirm_password


class CheckOtpForm(forms.Form):
    code = forms.CharField(
        label='code',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'enter code'
            }
        ),
        validators=[
            validators.MaxLengthValidator(4),
        ]
    )

class LoginForm(forms.Form):
    phone = forms.CharField(
        label='Phone',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Phone'
            }
        ),
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password'
            }
        ),
    )

    def clean(self):
        if self.is_valid():
            phone = self.cleaned_data['phone']
            password = self.cleaned_data['password']
            if not authenticate(phone=phone, password=password):
                raise forms.ValidationError("Phone Or Password Is Wrong")

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages
from random import randint
from .forms import RegisterForm, LoginForm, CheckOtpForm
from .models import Otp

User = get_user_model()


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # send sms here
            receptor = cd['phone']
            rand_code = randint(1000, 9999)
            print(rand_code)
            # end
            Otp.objects.create(phone=cd['phone'], code=rand_code)

            messages.success(request, 'Code Sent To Your Phone.')
            return redirect(reverse('accounts:check_otp') + f'?phone={receptor}')


class CheckTopView(View):
    def get(self, request):
        form = CheckOtpForm()
        return render(request, 'accounts/check_otp.html', {'form': form})

    def post(self, request):
        form = CheckOtpForm(request.POST)
        phone = request.GET.get('phone')
        if form.is_valid():
            cd = form.cleaned_data
            if Otp.objects.filter(phone=phone, code=cd['code']).exists():
                user = User.objects.create(phone=phone)
                # login(request, user)
                messages.success(request, 'Register Was Successful.')
                return redirect('shop:index')
        else:
            messages.warning(request, 'Something Went Wrong.')
            return redirect(request.META.get('HTTP_REFERER'))


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['phone'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'Logged In Successfully.')
                return redirect(request.META.get('HTTP_REFERER'))

accounts/templates/accounts/check_otp.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase text-center mx-xl-5 mb-4"><span
                class="bg-secondary pr-3">Verify Code</span></h2>
        <div class="px-xl-5">
            <div class="mb-5 contact-us" style="">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form action="{% url 'accounts:register' %}" method="post">
                        {% csrf_token %}
                        <div class="control-group">
                            {{ form.non_field_errors }}
                            {{ form.code }}
                            <p class="help-block text-danger"></p>
                        </div>

                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">
                                Verify
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase text-center mx-xl-5 mb-4"><span
                class="bg-secondary pr-3">Login</span></h2>
        <div class="px-xl-5">
            <div class="mb-5 contact-us" style="">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form action="{% url 'accounts:login' %}" method="post">
                        {% csrf_token %}
                        <div class="control-group">
                            {{ form.non_field_errors }}
                            {{ form.phone }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            {{ form.password }}
                            <p class="help-block text-danger"></p>
                        </div>

                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">
                                Login
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase text-center mx-xl-5 mb-4"><span
                class="bg-secondary pr-3">Register</span></h2>
        <div class="px-xl-5">
            <div class="mb-5 contact-us" style="">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form action="{% url 'accounts:register' %}" method="post">
                        {% csrf_token %}
                        <div class="control-group">
                            {{ form.non_field_errors }}
                            {{ form.phone }}
                            <p class="help-block text-danger"></p>
                        </div>

                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">
                                Register
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}